import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { parseSafeSvg } from './icon-parser.mjs'

const rootDir = resolve(import.meta.dirname, '..')
const checkOnly = process.argv.includes('--check')
if (!checkOnly) await mkdir(resolve(rootDir, 'src/icons/generated'), { recursive: true })
const sets = {
  normal: (name) => `mc-${name}`,
  key: (name) => (name.startsWith('key-') ? `mc-${name}` : `mc-key-${name}`),
  x: (name) => `mc-x-${name}`,
}

for (const [type, getName] of Object.entries(sets)) {
  const sourceDir = resolve(rootDir, 'src/assets/icons', type)
  const files = (await readdir(sourceDir)).filter((file) => file.endsWith('.svg')).sort()
  const icons = {}
  for (const file of files) {
    const base = file.replace(/\.svg$/i, '')
    const name = getName(base)
    const svg = await readFile(resolve(sourceDir, file), 'utf8')
    icons[name] = {
      name,
      type,
      colorable: type === 'normal',
      node: parseSafeSvg(svg, { source: `${type}/${file}`, colorable: type === 'normal' }),
    }
  }
  const exportName = `generatedMc${type[0].toUpperCase()}${type.slice(1)}Icons`
  const output = [
    "import type { McIconDefinition } from '../../framework/types'",
    '',
    `// Generated by scripts/generate-icons.mjs from validated SVG assets.`,
    `export const ${exportName}: Record<string, McIconDefinition> = ${JSON.stringify(icons, null, 2)}`,
    '',
  ].join('\n')
  const target = resolve(rootDir, 'src/icons/generated', `${type}.ts`)
  if (checkOnly) {
    const current = await readFile(target, 'utf8')
    if (current !== output) throw new Error(`${target} is stale; run npm run generate:icons`)
  } else {
    await writeFile(target, output, 'utf8')
  }
  process.stdout.write(`${checkOnly ? 'Checked' : 'Generated'} ${files.length} ${type} icons.\n`)
}
