import { readFileSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import postcss from 'postcss'
import { describe, expect, it } from 'vitest'

const rootDir = process.cwd()
const componentsDir = resolve(rootDir, 'src/components')
const stylesDir = resolve(rootDir, 'src/styles')
const componentNames = readdirSync(componentsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && /^Mc[A-Z]/.test(entry.name))
  .map((entry) => entry.name)
  .sort()
const sharedStyleNames = readdirSync(resolve(stylesDir, 'shared'))
  .filter((file) => file.endsWith('.css'))
  .sort()
const componentClassOwners = componentNames
  .map((name) => ({
    name,
    className: name
      .replace(/^Mc/, 'mc-')
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .toLowerCase(),
  }))
  .sort((a, b) => b.className.length - a.className.length)

function ownerOfClass(className: string) {
  return componentClassOwners.find(
    (owner) =>
      className === owner.className ||
      className.startsWith(`${owner.className}__`) ||
      className.startsWith(`${owner.className}--`),
  )?.name
}

describe('component style ownership', () => {
  it('co-locates a public entry and styles with every component', () => {
    expect(componentNames).toHaveLength(63)
    for (const name of componentNames) {
      const componentDir = resolve(componentsDir, name)
      const vue = readFileSync(resolve(componentDir, `${name}.vue`), 'utf8')
      const entry = readFileSync(resolve(componentDir, 'index.ts'), 'utf8')
      const style = readFileSync(resolve(componentDir, 'style.css'), 'utf8')
      readFileSync(resolve(componentDir, 'component.css'), 'utf8')

      expect(vue, name).not.toMatch(/<style(?:\s|>)/)
      expect(entry, name).not.toMatch(/import\s+['"][^'"]+\.css['"]/)
      expect(entry, name).toContain(`from './${name}.vue'`)
      expect(style.trim(), name).toBe("@import './component.css';")

      const componentCss = readFileSync(resolve(componentDir, 'component.css'), 'utf8')
      expect(vue.includes("import './style.css'"), name).toBe(componentCss.includes('{'))

      const expectsInputControl = vue.includes('class="mc-input')
      const cssImports = Array.from(vue.matchAll(/import\s+['"]([^'"]+\.css)['"]/g), (match) => match[1])
      expect(cssImports, name).toEqual([
        '../../styles/component-core.css',
        ...(expectsInputControl ? ['../../styles/shared/input-control.css'] : []),
        ...(componentCss.includes('{') ? ['./style.css'] : []),
      ])
      expect(componentCss, name).not.toMatch(/@import\b/)
    }
  })

  it('keeps the generated full aggregate deterministic and Utilities opt-in', () => {
    const aggregate = readFileSync(resolve(stylesDir, 'components.css'), 'utf8')
    const expected = [
      '/* Generated by scripts/generate-components.mjs. Do not edit directly. */',
      "@import './component-core.css';",
      ...sharedStyleNames.map((file) => `@import './shared/${file}';`),
      ...componentNames.map((name) => `@import '../components/${name}/component.css';`),
      '',
    ].join('\n')

    expect(aggregate).toBe(expected)
    expect(aggregate).not.toContain('utilities.css')
    expect(readFileSync(resolve(stylesDir, 'component-core.css'), 'utf8')).toContain("@import './tokens.css';")
  })

  it('allows only namespaced selectors in default component CSS', () => {
    const files = [
      resolve(stylesDir, 'component-core.css'),
      ...sharedStyleNames.map((file) => resolve(stylesDir, 'shared', file)),
      ...componentNames.map((name) => resolve(componentsDir, name, 'component.css')),
    ]

    for (const file of files) {
      const root = postcss.parse(readFileSync(file, 'utf8'), { from: file })
      root.walkRules((rule) => {
        if (rule.parent?.type === 'atrule' && /keyframes$/i.test(rule.parent.name)) return
        for (const selector of rule.selectors) {
          expect(selector.trim(), `${file}: ${selector}`).toMatch(
            /^(?:\.mc-|\.mc-theme|\[data-mc-theme|:where\(\.mc-theme\))/,
          )
        }
      })
    }
  })

  it('keeps shared styles neutral and component selectors local to their owner', () => {
    for (const file of sharedStyleNames) {
      const source = readFileSync(resolve(stylesDir, 'shared', file), 'utf8')
      expect(source, file).not.toMatch(/@import\b/)
      for (const match of source.matchAll(/\.((?:mc-)[a-z0-9_-]+)/g)) {
        expect(ownerOfClass(match[1]), `${file}: .${match[1]}`).toBeUndefined()
      }
    }

    for (const name of componentNames) {
      const source = readFileSync(resolve(componentsDir, name, 'component.css'), 'utf8')
      for (const match of source.matchAll(/\.((?:mc-)[a-z0-9_-]+)/g)) {
        const owner = ownerOfClass(match[1])
        if (!owner) continue
        expect(owner, `${name} styles reference ${owner} selector .${match[1]}`).toBe(name)
      }
    }
  })
})
